---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - helm.io.github.sfotiadis
  resources:
  - helmreboots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.io.github.sfotiadis
  resources:
  - helmreboots/finalizers
  verbs:
  - update
- apiGroups:
  - helm.io.github.sfotiadis
  resources:
  - helmreboots/status
  verbs:
  - get
  - patch
  - update
