name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'chart/Chart.yaml'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version to release'
        required: true
        default: '0.1.0'

env:
  REGISTRY: ghcr.io
  CHART_NAME: helmreboot-operator

jobs:
  release-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.13.0'

    - name: Extract version from release
      id: version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"  # Remove 'v' prefix
        else
          VERSION="${{ github.event.inputs.version }}"
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Chart version: ${VERSION}"

    - name: Update Chart.yaml version
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        sed -i "s/^version:.*/version: ${VERSION}/" chart/Chart.yaml
        sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" chart/Chart.yaml
        echo "Updated Chart.yaml to version ${VERSION}"

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Package and push Helm chart
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        
        # Package the chart
        helm package chart/ --version ${VERSION} --app-version ${VERSION}
        
        # Push to GHCR
        helm push helmreboot-operator-${VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}
        
        echo "Chart pushed: oci://ghcr.io/${{ github.repository_owner }}/helmreboot-operator:${VERSION}"

    - name: Generate chart installation instructions
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        echo "## 📦 Helm Chart Released!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Chart Version:** \`${VERSION}\`" >> $GITHUB_STEP_SUMMARY  
        echo "**Registry:** \`oci://ghcr.io/${{ github.repository_owner }}/helmreboot-operator\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Install the chart:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "helm install helmreboot-operator oci://ghcr.io/${{ github.repository_owner }}/helmreboot-operator --version ${VERSION}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY