name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'chart/Chart.yaml'

env:
  REGISTRY: ghcr.io

jobs:
  release-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.13.0'

    - name: Get chart info from Chart.yaml
      id: chart
      run: |
        CHART_NAME=$(grep "^name:" chart/Chart.yaml | cut -d' ' -f2)
        VERSION=$(grep "^version:" chart/Chart.yaml | cut -d' ' -f2)
        echo "chart_name=${CHART_NAME}" >> $GITHUB_OUTPUT
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Chart name: ${CHART_NAME}"
        echo "Chart version: ${VERSION}"

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Package and push Helm chart
      run: |
        CHART_NAME="${{ steps.chart.outputs.chart_name }}"
        VERSION="${{ steps.chart.outputs.version }}"
        helm package chart/ --version ${VERSION}
        helm push ${CHART_NAME}-${VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}

    - name: Generate installation summary
      run: |
        CHART_NAME="${{ steps.chart.outputs.chart_name }}"
        VERSION="${{ steps.chart.outputs.version }}"
        echo "## Helm Chart Released!" >> $GITHUB_STEP_SUMMARY
        echo "**Chart:** \`${CHART_NAME}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** \`${VERSION}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Install:** \`helm install ${CHART_NAME} oci://ghcr.io/${{ github.repository_owner }}/${CHART_NAME} --version ${VERSION}\`" >> $GITHUB_STEP_SUMMARY
