name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
  workflow_dispatch:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
